
#Options that affect the added furnaces.
["Furnace Settings"]
	#A comma separated list of all vanilla recipes that should not be used by the brick furnaces. Example: "baked_potato,baked_potato_from_smoking,othermod:other_baked_food"
	recipeBlacklist = ""
	#If enabled, the vanilla blasting, smelting, and smoking recipes are used by the brick furnaces.
	vanillaRecipesEnabled = false
	#Cook time factor of all added brick furnaces in relation to corresponding vanilla furnaces. (i. e. 0.5 - half the time, 1.0 same time, 2.0 twice the time)
	#Range: 0.0 ~ 100.0
	cookTimeFactor = 1.0

