
["Flower Seeds"]
	#Dandelion Seed Recipe
	dandelionseed = true
	#Poppy Seed Recipe
	poppyseed = true
	#Blue Orchid Seed Recipe
	orchidseed = true
	#Allium Seed Recipe
	alliumseed = true
	#Azure Bluet Seed Recipe
	azureseed = true
	#Red Tulip Seed Recipe
	tulip_redseed = true
	#Orange Tulip Seed Recipe
	tulip_orangeseed = true
	#White Tulip Seed Recipe
	tulip_whiteseed = true
	#Pink Tulip Seed Recipe
	tulip_pinkseed = true
	#Oxeye Daisy Seed Recipe
	oxeyeseed = true
	#Lily of The Valley Seed Recipe
	lilyseed = true
	#Wither Rose Seed Recipe
	witherroseseed = false
	#CornFlower Seed Recipe
	cornflowerseed = true

["Flower Seeds Cyclic"]
	#Cyan Rose Seed Recipe. (Useless if Cyclic is not installed)
	cyanroseseed = false

["Flower Seeds Terra"]
	#dandelion_puff Seed Recipe. (Useless if Terra Incognita is not installed)
	dandelion_puffseed = true
	#chicory Seed Recipe. (Useless if Terra Incognita is not installed)
	chicoryseed = true
	#yarrow Seed Recipe. (Useless if Terra Incognita is not installed)
	yarrowseed = true
	#daffodil Seed Recipe. (Useless if Terra Incognita is not installed)
	daffodilseed = true
	#yellow_primrose Seed Recipe. (Useless if Terra Incognita is not installed)
	yellow_primroseseed = true
	#pink_primrose Seed Recipe. (Useless if Terra Incognita is not installed)
	pink_primroseseed = true
	#purple_primrose Seed Recipe. (Useless if Terra Incognita is not installed)
	purple_primroseseed = true
	#foxglove Seed Recipe. (Useless if Terra Incognita is not installed)
	foxgloveseed = true
	#wild_garlic Seed Recipe. (Useless if Terra Incognita is not installed)
	wild_garlicseed = true
	#marigold Seed Recipe. (Useless if Terra Incognita is not installed)
	marigoldseed = true
	#blue_lupine Seed Recipe. (Useless if Terra Incognita is not installed)
	blue_lupineseed = true
	#red_snapdragon Seed Recipe. (Useless if Terra Incognita is not installed)
	red_snapdragonseed = true
	#yellow_snapdragon Seed Recipe. (Useless if Terra Incognita is not installed)
	yellow_snapdragonseed = true
	#magenta_snapdragon Seed Recipe. (Useless if Terra Incognita is not installed)
	magenta_snapdragonseed = true
	#edelweiss Seed Recipe. (Useless if Terra Incognita is not installed)
	edelweissseed = true
	#saxifrage Seed Recipe. (Useless if Terra Incognita is not installed)
	saxifrageseed = true
	#alpine_pink Seed Recipe. (Useless if Terra Incognita is not installed)
	alpine_pinkseed = true
	#gentian Seed Recipe. (Useless if Terra Incognita is not installed)
	gentianseed = true
	#forget_me_not Seed Recipe. (Useless if Terra Incognita is not installed)
	forget_me_notseed = true
	#globeflower Seed Recipe. (Useless if Terra Incognita is not installed)
	globeflowerseed = true
	#blue_iris Seed Recipe. (Useless if Terra Incognita is not installed)
	blue_irisseed = true
	#purple_iris Seed Recipe. (Useless if Terra Incognita is not installed)
	purple_irisseed = true
	#black_iris Seed Recipe. (Useless if Terra Incognita is not installed)
	black_irisseed = true
	#fireweed Seed Recipe. (Useless if Terra Incognita is not installed)
	fireweedseed = true
	#arctic_poppy Seed Recipe. (Useless if Terra Incognita is not installed)
	arctic_poppyseed = true
	#white_dryad Seed Recipe. (Useless if Terra Incognita is not installed)
	white_dryadseed = true

