#A list of blocks that allow paths under them. Format: modid:name:propertyname1=propertyvalue1,propertyname2=propertyvalue2,...
#Examples: "ore:glass", "minecraft:*", "minecraft:stone", "minecraft:oak_stairs:facing=east", "minecraft:oak_stairs:half=top", "minecraft:oak_stairs:facing=east,half=top"
#Each entry must be surrounded by double quotes
blocksWhitelist = []
#A list of blocks that disallow paths under them. Format: modid:name:propertyname1=propertyvalue1,propertyname2=propertyvalue2,...
#Examples: "ore:glass", "minecraft:*", "minecraft:stone", "minecraft:oak_stairs:facing=east", "minecraft:oak_stairs:half=top", "minecraft:oak_stairs:facing=east,half=top"
#Each entry must be surrounded by double quotes
blocksBlacklist = []

