
[general]
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	true_shot = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	exploding = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	butterfingers = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	shadow = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	phasing = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	resistant = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	solar = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	grappling = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	backtothechamber = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	equalmine = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	shattering = "ANVIL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	transposition = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	reflect = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	fumbling = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	dungeoneering = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	floating = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	ricochet = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	magnetic = "DISABLED"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	homing = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	torches = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	snatching = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	swift = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	breaking = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	harvest = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	combo = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	paralysis = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	teleportation = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	disarm = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	momentum = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	eternal = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	golbal_traveller = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	discord = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	instant_death = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	cursedjumping = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	stonelover = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	deflect = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	stonebound = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	lumberjack = "DISABLED"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	obsidian_buster = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	true_lifesteal = "NORMAL"
	#NORMAL,ANVIL,DISABLED
	#Allowed Values: DISABLED, ANVIL, NORMAL
	quickdraw = "NORMAL"

