
[minecraft]
	replace_zombie_horse = true
	replace_bee = true
	replace_wolf = true
	replace_skeleton_horse = true
	replace_donkey = true
	replace_ocelot = true
	replace_fox = true
	replace_polar_bear = true
	replace_horse = true
	replace_mule = true
	replace_cat = true
	replace_mooshroom = true
	replace_silverfish = true
	replace_squid = true
	replace_spider = true
	replace_sheep = true
	replace_cavespider = true
	replace_cow = true
	replace_pig = true
	replace_chicken = true
	replace_dolphin = true

[quark_compat]
	#use our own Quark-like variant textures. minecraft/replace_cow must be enabled as well.
	override_quark_cow = true
	#use our own Quark-like variant textures. minecraft/replace_pig must be enabled as well.
	override_quark_pig = true
	#use our own Quark-like textures. minecraft/replace_chicken must be enabled as well.
	override_quark_chicken = true
	#adds a shiny variant of our own. minecraft/replace_dolphin must be enabled as well.
	override_quark_dolphin = true

