
#General settings
[general]
	#Set this value to change the thread pool size of asynchronous crock pot recipe matching.
	#Range: 1 ~ 16
	asyncRecipeMatchingPoolSize = 1
	#Set this to false to disable asynchronous crock pot recipe matching.
	asyncRecipeMatching = true
	#Set this to false to disable new players spawning with the Crock Pot Cookbook.
	spawnWithBook = true

#World generation settings
[worldgen]
	#Set this to false will disable asparagus world generation.
	asparagusGeneration = true
	#Set this to false will disable tomato world generation.
	tomatoGeneration = true
	#Set this value to change the chance of corn world generation. The higher value, the less generation.
	#Range: > 1
	cornGenerationChance = 16
	#Set this to false will disable eggplant world generation.
	eggplantGeneration = true
	#Set this to false will disable onion world generation.
	onionGeneration = true
	#Set this value to change the chance of eggplant world generation. The higher value, the less generation.
	#Range: > 1
	eggplantGenerationChance = 16
	#Set this value to change the chance of tomato world generation. The higher value, the less generation.
	#Range: > 1
	tomatoGenerationChance = 16
	#Set this value to change the chance of asparagus world generation. The higher value, the less generation.
	#Range: > 1
	asparagusGenerationChance = 16
	#Set this value to change the chance of onion world generation. The higher value, the less generation.
	#Range: > 1
	onionGenerationChance = 16
	#Set this to false will disable corn world generation.
	cornGeneration = true

