
#EmbellishCraft General Config
[general_config]
	#Enable the logs for worldgen, useful to check if your config file is correct. This is client-side only. [default: false]
	EnableGenLogs = false

