
#Client-Side Settings
[client]
	#Defines the scale factor of the font for the Field Manual
	#Range: 0.1 ~ 3.0
	manualFontScale = 0.75
	#The X-position of the Prospector's Pickaxe Depth HUD
	#Range: > 0
	propickHUDX = 2
	#The Y-position of the Prospector's Pickaxe Depth HUD
	#Range: > 0
	propickHUDY = 2
	#Enable Minecraft object tag tooltip with Advanced Tooltips on (F3+"H")
	enableTagDebug = true
	#When using a prospector's pick, blocks located nearby are highlighted ONLY when below ground. The server owner has control of this functionality, so if this is enabled and on a server it isn't, this effect will not work.
	enableDepositHighlight = true
	#How long these highlights (if enabled) should stay around for (in seconds)
	#Range: > 1
	depositHighlightDuration = 15

