
#Feature Control
["feature control"]
	#Output info into the logs when generating Geolosys deposits
	debugWorldgen = false
	#Outputs really advanced info when generating deposits.
	advancedDebugWorldGen = false
	#Disable generation of Vanilla ores
	disableVanillaOreGen = false
	#The fallback materials which a Deposit can replace if they're not specified by the deposit itself
	#Format: Comma-delimited set of <modid:block> (see default for example)
	defaultReplacementMaterials = ["minecraft:stone", "minecraft:andesite", "minecraft:diorite", "minecraft:granite", "minecraft:netherrack", "minecraft:sandstone"]

#Prospecting Options
[prospecting]
	#Maximum samples that can generate with each pluton within a chunk
	#Range: 1 ~ 256
	maxSamplesPerChunk = 10
	#The upper limit of RNG for generating any pluton in a given chunk.
	#Larger values indicate further distance between plutons.
	#Range: > 1
	chunkSkipChance = 100
	#A list of <modid:block> that samples may not be placed on
	samplePlacementBlacklist = ["minecraft:ice", "minecraft:packed_ice", "minecraft:bedrock"]
	#Enable the prospector's pickaxe
	enableProPick = true
	#Allow the prospector's pick to get damaged
	enableProPickDmg = false
	#Max durability of a prospector's pick if damage is enabled
	#Range: > 1
	proPickDurability = 1024
	#The range (depth) of the prospector's pick prospecting cycle
	#Range: > 1
	proPickRange = 5
	#The diameter of the prospector's pick prospecting cycle
	#Range: > 1
	proPickDiameter = 5
	#Give players a Field Manual if they haven't gotten one
	giveManual = true
	#When using a prospector's pick, blocks located nearby are highlighted ONLY when below ground.
	enableDepositHighlight = true

#Mod-Compat Settings
[compat]
	#This will make it so that Platinum will drop Platinum AND Osmium
	enableOsmium = true
	#This will make it so that Platinum will ONLY drop Osmium
	enableOsmiumExclusively = true
	#This will make it so that Autunite will drop Uranium AND Yellorium
	enableYellorium = true
	#This will make is so that Coal has a rare chance of dropping sulfur
	enableSulfur = true

