#This option makes guards run from ravagers when low on health
"Have Guards be run from ravagers when on low health?" = true
#This makes villagers run from polar bears, as anyone with common sense would.
"Have Villagers have some common sense?" = true
#This makes Illagers run from polar bears, as anyone with common sense would.
"Have Illagers have some common sense?" = true
#This makes Guards run from polar bears, as anyone with common sense would.
"Have Guards have some common sense?" = false
#This lets Guards open doors.
"Have Guards open doors?" = true
#This will make guards raise their shields all the time, on default they will only raise their shields under certain conditions
"Have Guards raise their shield all the time?" = false
#This makes guards form a phalanx
"Have guards form a phalanx?" = true
#Illagers In Raids Attack Animals?
"Illagers in raids attack animals?" = false
#Witches Attack Villagers?
"Witches attack villagers?" = true
#This will make Illusioners get involved in raids
"Have Illusioners in raids?" = true
#Guards will attack all hostiles with this option
"Guards attack all mobs?" = false
#Guards won't attack mobs in this list if AttackAllMobs is enabled, for example, putting minecraft:creeper in this list will make guards ignore creepers.
"Mob BlackList" = []
#This will make guards attempt to avoid friendly fire.
"Have guards avoid friendly fire? (Experimental)" = false
#This will make it so villagers will only be converted into guards if the player has hero of the village
"Make it so players have to have hero of the village to convert villagers into guards?" = false
"Have it so blacksmiths heal golems under 60 health?" = true
"Have it so clerics heal guards and players with hero of the village?" = true

