
#Settings for world gen
["World Gen"]
	#Average chunk separation between companion houses
	#Range: > 11
	averageHouseSeparation = 20

[Other]
	#Toggle friendly fire
	friendlyFire = false

