#Enables the mod to decorate underground structures and allows for more compatibility with other terrain gen mods at the expense of slower performance. Note that caves in worlds with the same seed may be populated differently depending on this setting
"Expensive Scan" = true
#The amount of non-solid blocks in front of a cave wall at which stairs and slabs spawn at a reduced rate to avoid high density narrow caves
#Range: 0 ~ 16
"Slope Threshold" = 2
#The dimensions in which cave biomes will generate in
"Dimension Whitelist" = ["minecraft:overworld"]

