
[Tweaks]
	#Adds foxes, sheep, berry bushes, birches and shrubs to tundras to make them less lackluster.
	#Default: true
	"Better Tundras" = true
	#Adds composting recipes for dead bushes, bamboo, poisonous potatoes and chorus fruits/flowers.
	#Default: true
	"Additional Compostables" = true
	#Allows growing lilypads by using bonemeal in shallow water pools.
	#Default: true
	"Bonemeal Lilypad Growing" = true
	#If enabled, wither roses will generate naturally in Soul Sand Valleys.
	#Default: true
	"Wither Rose Generation" = true

[Biomes]
	#Adds snowless and rocky tundra biomes.
	#Default: true
	"Tundra Variants" = true

[Tools]
	#Caltrops are metal spikes that can be placed on the ground. Dropped caltrops will also place themselves if possible.
	#Caltrops deal one heart of damage and inflict slowness for 10 seconds when touched.
	#They break with 1 in 5 chance after dealing damage, so they are not suitable as a permanent trap.
	#Caltrops will be flushed away by flowing water.
	#You can right click caltrops with an empty hand to pick them up.
	#Default: true
	"Caltrops Enabled" = true
	#Basket is a portable container crafted from swamp reeds. It can be placed or opened from inventory.
	#Baskets have 9 slots and can only store flowers, saplings, mushrooms and berries by default (governed by #terraincognita:basket_storable item tag)
	#When you have a basket in your hand, it will automatically collect compatible items.
	#Default: true
	"Basket Enabled" = true

[Flora]
	#Dandelion puffs spawn among vanilla dandelions. You can blow on a dandelion puff by using it.
	#Default: true
	"Dandelion Puff Enabled" = true
	#Small lilypads can be found in swamps. They can be stacked up to 4, like sea pickles.
	#Default: true
	"Small Lilypads Enabled" = true
	#Lotus is a beautiful aquatic flower found in jungles. It comes in yellow, pink and white colors.
	#Default: true
	"Lotus Enabled" = true
	#Wreath is a cosmetic headdress crafted with 4 small flowers of any kind in any shape.
	#The color of the wreath depends on the flowers you used to craft it.
	#Default: true
	"Wreaths Enabled" = true
	#Chance to replace a vanilla dandelion with a dandelion puff during generation.
	#Default: 0.5
	#Range: 0.0 ~ 1.0
	"Dandelion Puff Ratio" = 0.5
	#Adds forget-me-not to temperate and hot swamps.
	#Default: true
	"Swamp Flowers Enabled" = true
	#Reeds are a sugarcane-like plant that can be found in swamps. They can be grown in the same way as sugar cane, or, alternatively, in one block deep water.
	#Reeds can be crafted into a variety of decorative wicker blocks and baskets.
	#Default: true
	"Reeds Enabled" = true
	#Adds marigolds and blue lupins to savannas.
	#Marigolds are unique in that they can grow on sand, but only if there is water nearby. They will spawn in deserts when these conditions are met.
	#Default: true
	"Savanna Flowers Enabled" = true
	#Adds blue and purple irises to jungles.
	#Default: true
	"Jungle Flowers Enabled" = true
	#Adds edelweiss, alpine pink and rockfoil to temperate and cold mountain biomes.
	#All of these flowers can grow on gravel, and rockfoil can grow on stone as well.
	#Edelweiss has a minimum altitude requirement to generate.
	#Default: true
	"Alpine Flowers Enabled" = true
	#Minimum Y level where edelweiss can generate in the mountains.
	#Default: 90
	#Range: 64 ~ 128
	"Minimum Altitude for Edelweiss" = 90
	#Adds fireweed to taiga and tundra biomes.
	#Also adds arctic poppies that replace vanilla poppies in tundras.
	#Default: true
	"Arctic Flowers Enabled" = true
	#Roots can be found on dirt cave ceilings and overhangs in most biomes.
	#They can be collected with shears. You can grow more roots by using bonemeal on one.
	#Roots can be crafted into brown dye.
	#Default: true
	"Roots Enabled" = true

[Food]
	#Fern fiddleheads can be found when breaking ferns. You can eat them raw or add them to suspicious stews.
	#Duration of suspicious stew's effect is doubled when a fiddlehead is added during or after cooking.
	#If the effect is negative, duration is halved instead.
	#Default: true
	"Fern Fiddlehead Enabled" = true
	#Taffy is a food item that can only be found in dungeons. It restores some health, but also makes your mouth sticky, reducing eating speed with every taffy eaten.
	#Default: true
	"Taffy Enabled" = true
	#How many half hearts are healed when eating a taffy.
	#Default: 3
	#Range: 2 ~ 8
	"Taffy Healing Amount" = 3
	#Berry Sorbet is a new food item made with sweet berries, sugar and a snowball in a bowl.
	#Default: true
	"Berry Sorbet Enabled" = true
	#Baked root can be made by covering a root with clay and cooking it on a campfire.
	#It gives 15 seconds of Haste when eaten.
	#Default: true
	"Baked Root Enabled" = true
	#Enchanted golden carrot grants 30 seconds of Regeneration II, 2 minutes of Absorption IV, 5 minutes of Speed II and 10 minutes of Night Vision when eaten.
	#It can be found in dungeon loot with the same rarity as enchanted golden apples.
	#Default: true
	"Enchanted Golden Carrot Enabled" = true

