#[INTERNAL] Mod configuration version -- DO NOT ALTER, EVER!
version = 1

[general]
	#[INTERNAL] Development workflow enabled. Do NOT enable in regular environment. Applies only to library.
	debug_mode = false
	#Consider neutral potions as 'bad' for certain operations; for example, when blanket clearing harmful effects with antidotes. Affects all library-dependent mods.
	neutral_effects_bad = false
	#Set to "false" to disable direct integration with advanced survival mods like 'Survive'. Use this option if you want full control over all aspects of inter-mod integration with your survival framework and environment. Affects auto-integration of all library-dependent mods.
	survival_mods = "*DEFAULT*"
	#[INTERNAL] Set to the number of ticks associated with a FULL day-night cycle in game. Alter this value for debugging only; leave as-is to allow library to determine value from mods present.
	ticks_per_fullday = -1
	#[INTERNAL] Set to the number of ticks associated with just the day portion of a day-night cycle in game. Alter this value for debugging only; leave as-is to allow library to determine value from mods present.
	ticks_per_daytime = -1

